"""Compatibility wrapper for core mask manifest algorithms."""

from objgauss.core.masks import (
    LEGO_COLOR_SLOTS,
    AlphaFgBgMaskManifestResult,
    ColorMaskManifestResult,
    MaskManifestResult,
    MaskManifestSplitResult,
    MaskManifestValidationResult,
    SamMaskManifestResult,
    build_nerf_alpha_fgbg_mask_manifest,
    build_nerf_alpha_mask_manifest,
    build_nerf_rgba_color_mask_manifest,
    build_nerf_sam_mask_manifest,
    classify_lego_rgba,
    read_image_rgba,
    read_png_alpha,
    read_png_rgba,
    resize_rgba_max_size,
    resolve_nerf_image,
    slot_count_summary,
    split_mask_manifest,
    validate_mask_manifest,
)

__all__ = [
    "LEGO_COLOR_SLOTS",
    "AlphaFgBgMaskManifestResult",
    "ColorMaskManifestResult",
    "MaskManifestResult",
    "MaskManifestSplitResult",
    "MaskManifestValidationResult",
    "SamMaskManifestResult",
    "build_nerf_alpha_fgbg_mask_manifest",
    "build_nerf_alpha_mask_manifest",
    "build_nerf_rgba_color_mask_manifest",
    "build_nerf_sam_mask_manifest",
    "classify_lego_rgba",
    "read_image_rgba",
    "read_png_alpha",
    "read_png_rgba",
    "resize_rgba_max_size",
    "resolve_nerf_image",
    "slot_count_summary",
    "split_mask_manifest",
    "validate_mask_manifest",
]
