"""Deprecated compatibility import for trainable-kernel orchestration."""

from objgauss.pipelines.trainable_kernel import (
    TRAINABLE_IMAGE_TARGET_CONTRACT_SCHEMA,
    TRAINABLE_IMAGE_TARGET_SCHEMA,
    TRAINABLE_KERNEL_MVP_SCHEMA,
    TRAINING_IMAGE_RENDERERS,
    TRAINING_IMAGE_RENDERER_GSPLAT,
    TRAINING_IMAGE_RENDERER_POINT,
    TrainableKernelCamera,
    TrainableKernelFrame,
    TrainableKernelImageTarget,
    TrainableKernelLoss,
    TrainableKernelResult,
    TrainableKernelSample,
    bind_image_targets_to_frames,
    image_target_contract_summary,
    make_trainable_image_target,
    make_trainable_kernel_mvp_fixture,
    train_kernel_mvp,
    train_kernel_mvp_from_cloud,
    trainable_kernel_sample_from_cloud,
    validate_image_target_contract_summary,
    validate_trainable_image_target,
)

__all__ = (
    "TRAINABLE_KERNEL_MVP_SCHEMA",
    "TRAINABLE_IMAGE_TARGET_CONTRACT_SCHEMA",
    "TRAINABLE_IMAGE_TARGET_SCHEMA",
    "TRAINING_IMAGE_RENDERER_POINT",
    "TRAINING_IMAGE_RENDERER_GSPLAT",
    "TRAINING_IMAGE_RENDERERS",
    "TrainableKernelCamera",
    "TrainableKernelImageTarget",
    "TrainableKernelFrame",
    "TrainableKernelLoss",
    "TrainableKernelResult",
    "TrainableKernelSample",
    "train_kernel_mvp",
    "train_kernel_mvp_from_cloud",
    "trainable_kernel_sample_from_cloud",
    "make_trainable_kernel_mvp_fixture",
    "bind_image_targets_to_frames",
    "make_trainable_image_target",
    "image_target_contract_summary",
    "validate_trainable_image_target",
    "validate_image_target_contract_summary",
)
