"""Deprecated compatibility import for synthetic v2 stability datasets."""

from objgauss.datasets.v2_stability_foundation import (
    V2_STABILITY_FOUNDATION_SCHEMA,
    V2_STABILITY_SCENARIO_FIXTURE_SCHEMA,
    V2_STABILITY_SCENARIO_KINDS,
    V2_SYNTHETIC_OBSERVATION_SCHEMA,
    ObjectIdentityObservation,
    ObjectIdentityOracle,
    ObjectIdentityRecord,
    ObservationModelConfig,
    SyntheticObservationFrame,
    SyntheticStabilityScenarioFixture,
    SyntheticWorldFrame,
    SyntheticWorldObject,
    SyntheticWorldState,
    make_object_identity_oracle,
    make_synthetic_stability_scenario_fixture,
    make_synthetic_stability_scenario_suite,
    make_synthetic_world_state,
    observe_synthetic_world,
    validate_object_identity_oracle,
    validate_observation_model_config,
    validate_synthetic_observation_frame,
    validate_synthetic_stability_scenario_fixture,
    validate_synthetic_world_frame,
    validate_synthetic_world_state,
)

__all__ = (
    "V2_STABILITY_FOUNDATION_SCHEMA",
    "V2_SYNTHETIC_OBSERVATION_SCHEMA",
    "V2_STABILITY_SCENARIO_FIXTURE_SCHEMA",
    "V2_STABILITY_SCENARIO_KINDS",
    "ObjectIdentityRecord",
    "ObjectIdentityObservation",
    "ObjectIdentityOracle",
    "SyntheticWorldObject",
    "SyntheticWorldFrame",
    "SyntheticWorldState",
    "ObservationModelConfig",
    "SyntheticObservationFrame",
    "SyntheticStabilityScenarioFixture",
    "make_object_identity_oracle",
    "make_synthetic_world_state",
    "make_synthetic_stability_scenario_fixture",
    "make_synthetic_stability_scenario_suite",
    "observe_synthetic_world",
    "validate_synthetic_stability_scenario_fixture",
    "validate_object_identity_oracle",
    "validate_synthetic_world_frame",
    "validate_synthetic_world_state",
    "validate_observation_model_config",
    "validate_synthetic_observation_frame",
)
