export const ASSET_LIBRARY = [
  {
    id: "plush-3dgs-local",
    name: "Plush 3DGS 示例",
    category: "本地样例",
    sourceType: "gaussian",
    status: "已接入",
    priority: "P0",
    pipelineStage: "Demo 可用",
    useCases: ["Demo预览", "管线烟测"],
    localPath: "/samples/plush_objects.ply",
    splatPath: "/samples/plush.splat",
    fileName: "plush_objects.ply",
    sourceName: "cakewalk/splat-data",
    sourceUrl: "https://huggingface.co/cakewalk/splat-data/blob/main/plush.splat",
    license: "来源许可混合，仅用于本地测试",
    formats: [".splat", ".ply", "object_id"],
    bestFor: "快速验证高斯点云加载、对象聚类色、删除/隔离预览。",
  },
  {
    id: "plush-v1-closure-local",
    name: "ObjGauss v1 闭环样例",
    category: "本地验收",
    sourceType: "gaussian",
    status: "已接入",
    priority: "P0",
    pipelineStage: "v1闭环验收",
    useCases: ["真实Splat", "ObjectField", "mask投票", "对象编辑"],
    localPath: "/samples/plush_v1_objects.ply",
    splatPath: "/samples/plush.splat",
    fileName: "plush_v1_objects.ply",
    sourceName: "ObjGauss demo v1-closure",
    sourceUrl: "https://huggingface.co/cakewalk/splat-data/blob/main/plush.splat",
    license: "来源许可混合，仅用于本地测试",
    formats: [".splat", ".ply", "object_id"],
    bestFor: "验证真实 3DGS 外观、Object Field、2D mask 投票和对象隔离/删除闭环。",
  },
  {
    id: "polyhaven-school-chair-1k",
    name: "Poly Haven School Chair 1K",
    category: "可商用展示",
    sourceType: "mesh",
    status: "已接入",
    priority: "P0",
    pipelineStage: "Demo 素材已自动化",
    useCases: ["展示Demo", "可商用样例", "mesh转3DGS"],
    sourceName: "Poly Haven",
    sourceUrl: "https://polyhaven.com/a/SchoolChair_01",
    license: "CC0；API 仅用于非商用/研究拉取",
    formats: [".gltf", ".bin", ".jpg", "CC0"],
    bestFor: "许可干净的单对象家具 Demo 输入，后续用于 mesh 多视角渲染和 3DGS 训练。",
  },
  {
    id: "nerf-synthetic-lego",
    name: "NeRF Synthetic Lego",
    category: "3DGS 训练集",
    sourceType: "images",
    status: "已接入",
    priority: "P0",
    pipelineStage: "训练源已自动化",
    useCases: ["3DGS训练", "ObjectField烟测"],
    sourceName: "bmild/nerf",
    sourceUrl: "https://github.com/bmild/nerf",
    license: "NeRF 官方示例数据，仅训练/研究使用",
    formats: ["images", "transforms_train.json", "transforms_test.json"],
    bestFor: "ObjGauss v1 Object Field 的多视角训练烟测和跨视角一致性验证。",
  },
  {
    id: "arkitscenes",
    name: "ARKitScenes",
    category: "真实室内场景",
    sourceType: "scan",
    status: "候选",
    priority: "P0",
    pipelineStage: "训练源",
    useCases: ["3DGS训练", "室内Demo"],
    sourceName: "apple/ARKitScenes",
    sourceUrl: "https://github.com/apple/ARKitScenes",
    license: "按 Apple 数据许可执行",
    formats: ["RGB-D", "pose", "mesh", "3D bbox"],
    bestFor: "贴近手机 LiDAR 扫描输入，适合做房间和家具级对象化实验。",
  },
  {
    id: "scannet",
    name: "ScanNet",
    category: "真实室内场景",
    sourceType: "scan",
    status: "候选",
    priority: "P1",
    pipelineStage: "训练源",
    useCases: ["分割评估", "训练验证"],
    sourceName: "ScanNet",
    sourceUrl: "https://www.scan-net.org/",
    license: "研究数据许可，需申请",
    formats: ["RGB-D", "pose", "mesh", "semantic"],
    bestFor: "有语义/实例标注，适合验证场景到对象分组的准确性。",
  },
  {
    id: "omniobject3d",
    name: "OmniObject3D",
    category: "对象级扫描",
    sourceType: "mesh",
    status: "候选",
    priority: "P0",
    pipelineStage: "训练源",
    useCases: ["对象训练", "对象Demo"],
    sourceName: "OmniObject3D",
    sourceUrl: "https://omniobject3d.github.io/",
    license: "按数据集条款执行",
    formats: ["mesh", "point cloud", "multi-view"],
    bestFor: "高质量真实扫描对象，适合做单物体高斯化和对象级编辑。",
  },
  {
    id: "google-scanned-objects",
    name: "Google Scanned Objects",
    category: "对象级扫描",
    sourceType: "mesh",
    status: "候选",
    priority: "P1",
    pipelineStage: "训练源",
    useCases: ["物理代理", "对象Demo"],
    sourceName: "Google Research",
    sourceUrl:
      "https://research.google/blog/scanned-objects-by-google-research-a-dataset-of-3d-scanned-common-household-items/",
    license: "CC-BY 4.0",
    formats: ["OBJ", "SDF", "texture", "collider"],
    bestFor: "日用品和机器人仿真，适合后续 collider proxy / 物理代理。",
  },
  {
    id: "poly-haven",
    name: "Poly Haven",
    category: "可商用展示",
    sourceType: "mesh",
    status: "候选",
    priority: "P0",
    pipelineStage: "Demo 素材",
    useCases: ["展示Demo", "可商用样例"],
    sourceName: "Poly Haven",
    sourceUrl: "https://polyhaven.com/models",
    license: "CC0",
    formats: ["blend", "glTF", "textures"],
    bestFor: "快速搭展示 demo，许可干净，适合开源项目里的可复现素材。",
  },
  {
    id: "mipnerf360",
    name: "Mip-NeRF 360",
    category: "3DGS 训练集",
    sourceType: "images",
    status: "候选",
    priority: "P1",
    pipelineStage: "训练源",
    useCases: ["3DGS训练", "渲染评估"],
    sourceName: "3D Gaussian Splatting 官方页面",
    sourceUrl: "https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/",
    license: "按原数据集条款执行",
    formats: ["images", "COLMAP", "poses"],
    bestFor: "训练 3DGS 和评估新视角渲染质量。",
  },
  {
    id: "tanks-and-temples",
    name: "Tanks and Temples",
    category: "3DGS 训练集",
    sourceType: "images",
    status: "候选",
    priority: "P2",
    pipelineStage: "训练源",
    useCases: ["重建评估", "论文验证"],
    sourceName: "Tanks and Temples",
    sourceUrl: "https://www.tanksandtemples.org/",
    license: "按 benchmark 条款执行",
    formats: ["images", "video", "ground truth"],
    bestFor: "复杂真实场景重建 benchmark，适合后期质量评估。",
  },
];

export const FEATURED_ASSET_IDS = [
  "plush-v1-closure-local",
  "plush-3dgs-local",
  "polyhaven-school-chair-1k",
  "nerf-synthetic-lego",
  "arkitscenes",
  "omniobject3d",
  "mipnerf360",
  "google-scanned-objects",
];

export function featuredAssets() {
  const ids = new Set(FEATURED_ASSET_IDS);
  return ASSET_LIBRARY.filter((asset) => ids.has(asset.id));
}
