export const MODEL_CATALOG = [
  {
    id: "plush",
    name: "Plush object scene",
    label: "Plush",
    sourcePath: "/samples/plush_objects.ply",
    loadMode: "eager",
    kind: "object-aware-ply",
    stage: "processed",
    objectCount: 3,
    galleryPosition: [-6.2, 0, -1.35],
    accent: "#ff6b7a",
    displayScale: 2.42,
    pointSize: 0.034,
    minObjectDisplaySpan: 1.22,
    maxObjectDisplayBoost: 5.2,
    maxDisplayPoints: 34000,
    compression: {
      layout: "per-object-corepoint-chunks",
      status: "planned",
      chunkRoot: "/models/plush/objects/",
    },
  },
  {
    id: "plush-v1",
    name: "ObjGauss v1 closure",
    label: "Plush v1",
    sourcePath: "/samples/plush_v1_objects.ply",
    loadMode: "eager",
    kind: "object-aware-ply",
    stage: "processed",
    objectCount: 4,
    galleryPosition: [-3.15, 0, 1.55],
    accent: "#f7b267",
    displayScale: 2.34,
    pointSize: 0.034,
    minObjectDisplaySpan: 1.08,
    maxObjectDisplayBoost: 4.6,
    maxDisplayPoints: 34000,
    compression: {
      layout: "per-object-corepoint-chunks",
      status: "planned",
      chunkRoot: "/models/plush-v1/objects/",
    },
  },
  {
    id: "lego-alpha",
    name: "Lego alpha closure",
    label: "Lego alpha",
    sourcePath: "/samples/lego_alpha_v1_objects.ply",
    loadMode: "eager",
    kind: "object-aware-ply",
    stage: "processed",
    objectCount: 5,
    galleryPosition: [0.05, 0, -1.25],
    accent: "#27c2cb",
    displayScale: 2.46,
    pointSize: 0.035,
    minObjectDisplaySpan: 1.08,
    maxObjectDisplayBoost: 4.8,
    maxDisplayPoints: 26000,
    compression: {
      layout: "per-object-corepoint-chunks",
      status: "planned",
      chunkRoot: "/models/lego-alpha/objects/",
    },
  },
  {
    id: "polyhaven-chair",
    name: "Poly Haven chair",
    label: "Chair",
    sourcePath: "/samples/polyhaven_chair_demo_objects.ply",
    loadMode: "eager",
    kind: "object-aware-ply",
    stage: "processed",
    objectCount: 1,
    galleryPosition: [3.25, 0, 1.42],
    accent: "#88d498",
    displayScale: 2.14,
    pointSize: 0.033,
    maxDisplayPoints: 36000,
    compression: {
      layout: "per-object-corepoint-chunks",
      status: "planned",
      chunkRoot: "/models/polyhaven-chair/objects/",
    },
  },
  {
    id: "near1m-lego",
    name: "Near-1M Lego candidate",
    label: "Near-1M",
    sourcePath: "/samples/nerf_lego_trained_near1m_random1300k_objects.ply",
    loadMode: "compressed-placeholder",
    kind: "diagnostic-ply",
    stage: "diagnostic",
    objectCount: 5,
    galleryPosition: [6.35, 0, -1.42],
    accent: "#8e6cff",
    displayScale: 2.28,
    pointSize: 0.042,
    placeholderPointsPerObject: 820,
    maxDisplayPoints: 45000,
    compression: {
      layout: "per-object-corepoint-chunks",
      status: "prototype",
      chunkRoot: "/models/near1m-lego/objects/",
    },
  },
];

export function catalogSummary(models = MODEL_CATALOG) {
  return {
    modelCount: models.length,
    compressedReadyCount: models.filter((model) => model.compression?.status === "prototype").length,
    processedCount: models.filter((model) => model.stage === "processed").length,
  };
}
