import {
  QUANTIZED_OGC_PAYLOAD_SCHEMA,
  QUANTIZED_OGC_RECORD_BYTE_SIZE,
  QUANTIZED_OGC_RECORD_FORMAT,
} from "./ogcDecoder.js";
import { MODEL_ARTIFACT_MANIFEST_SCHEMA } from "./modelArtifactManifest.js";

const OGC_DEBUG_PAYLOAD_BASE64 =
  "AIAAAACA7GNY5uAuUEYgTv+VYM0gywhSEKTuzXfX8FVwlJi30FtwyMivsLOwNvi0U9IAgP//AID/6Z7rAIAAAACAJ8LL4YA+mDoIUnHc4s1Qw2hCgLtTod/SOEpYmFDDTNSsxpi3mLeYOpjYgtcAgP//AIDJ9pbo";

const TRAINABLE_MVP_DEBUG_ARTIFACT = {
  schema: "objgauss-trainable-kernel-model-artifact-v1",
  kind: "trainable_kernel_mvp_model",
  label: "trainable-mvp-debug-fixture",
  source: {
    input: "fixture://trainable-mvp-debug",
    sample: {
      slots: 2,
      frame_count: 2,
      source_count: 4,
      sampled_count: 4,
      target_source: "object_id_one_hot_targets",
    },
  },
  training: {
    schema: "objgauss-v1-trainable-kernel-mvp-v1",
    slots: 2,
    frame_count: 2,
    iterations: 18,
    weights: {
      render: 0,
      image_render: 1,
      object: 0,
      temporal: 0.02,
    },
    initial_loss: {
      total_loss: 0.082205,
      render_loss: 0.084134,
      image_render_loss: 0.082205,
      object_loss: 1.248721,
      temporal_loss: 0.00018,
    },
    final_loss: {
      total_loss: 0.053806,
      render_loss: 0.057232,
      image_render_loss: 0.053806,
      object_loss: 1.248721,
      temporal_loss: 0.00012,
    },
    image_render_loss_decreased: true,
    render_target_mode: "image_space_targets_bound",
  },
  renderer_api: {
    schema: "objgauss-training-renderer-api-v1",
    status: "ready",
    renderer_name: "cpu-image-point-splat-differentiable-v1",
    gradient_path: "analytic-color-assignment-gradient-v1",
    image_render_loss: 0.053806,
    differentiable_fields: ["decoder_colors", "assignments"],
    frozen_fields: ["positions", "camera", "visibility_mask", "point_radius"],
  },
  learned_parameters: {
    decoder_colors: [
      [0.899, 0.246, 0.162],
      [0.118, 0.686, 0.841],
    ],
  },
  assignments: [
    {
      frame_index: 0,
      shape: [4, 2],
      matrix: [
        [0.82, 0.18],
        [0.74, 0.26],
        [0.21, 0.79],
        [0.12, 0.88],
      ],
    },
    {
      frame_index: 1,
      shape: [4, 2],
      matrix: [
        [0.8, 0.2],
        [0.72, 0.28],
        [0.24, 0.76],
        [0.14, 0.86],
      ],
    },
  ],
  object_states: [
    {
      frame_index: 0,
      derived_object_ids: [0, 0, 1, 1],
      states: [
        {
          id: 0,
          slot_mass: 2.18,
          confidence: 0.78,
          mass_fraction: 0.545,
          assignment_entropy: 0.515,
          normalized_assignment_entropy: 0.743,
          centroid: [-0.78, 0.42, -0.04],
          bbox: [-1.14, 0, -0.34, -0.36, 0.86, 0.28],
          status: "active_trained_slot",
          diagnostics: [],
        },
        {
          id: 1,
          slot_mass: 1.82,
          confidence: 0.835,
          mass_fraction: 0.455,
          assignment_entropy: 0.421,
          normalized_assignment_entropy: 0.607,
          centroid: [0.78, 0.46, 0.04],
          bbox: [0.34, 0, -0.3, 1.18, 0.92, 0.34],
          status: "active_trained_slot",
          diagnostics: [],
        },
      ],
    },
    {
      frame_index: 1,
      derived_object_ids: [0, 0, 1, 1],
      states: [
        {
          id: 0,
          slot_mass: 2.16,
          confidence: 0.76,
          mass_fraction: 0.54,
          assignment_entropy: 0.535,
          normalized_assignment_entropy: 0.772,
          centroid: [-0.762, 0.422, -0.034],
          bbox: [-1.12, 0, -0.33, -0.34, 0.87, 0.29],
          status: "active_trained_slot",
          diagnostics: [],
        },
        {
          id: 1,
          slot_mass: 1.84,
          confidence: 0.81,
          mass_fraction: 0.46,
          assignment_entropy: 0.439,
          normalized_assignment_entropy: 0.633,
          centroid: [0.796, 0.462, 0.046],
          bbox: [0.36, 0, -0.28, 1.2, 0.93, 0.36],
          status: "active_trained_slot",
          diagnostics: [],
        },
      ],
    },
  ],
  artifact_policy: {
    intended_location: "debug fixture",
    git_policy: "small_static_fixture_only",
    viewer_policy: "ObjectState Debug OS fixture, not production model",
  },
};

const OGC_DEBUG_INDEX = {
  schema: "objgauss-chunk-index-v1",
  sort_key: "object_id+morton_xyz",
  gaussian_count: 12,
  object_count: 2,
  chunk_size_target: 6,
  payload: {
    schema: QUANTIZED_OGC_PAYLOAD_SCHEMA,
    path: "inline://ogc-debug.ogc",
    format: ".ogc",
    record_format: QUANTIZED_OGC_RECORD_FORMAT,
    record_byte_size: QUANTIZED_OGC_RECORD_BYTE_SIZE,
    byte_size: 120,
    sha256: "673f6782c9c9e4d50318e0dcb41276b2167084a1da8894e820e0e8487ca7ecd9",
  },
  compression: {
    codec: "objgauss-ogc-prototype",
    layout: "object-aware-chunked-local-quantized",
    quantization: {
      schema: "objgauss-local-quantization-v1",
      policy: "chunk-aabb-uint16-rgb8-opacity8-v0",
      status: "actual_payload_prototype",
    },
  },
  lod: {
    schema: "objgauss-object-aware-lod-v1",
    levels: [
      { level: 0, ratio: 1.0, gaussian_count: 12 },
      { level: 1, ratio: 0.5, gaussian_count: 6 },
    ],
  },
  object_id_coverage: {
    field: "object_id",
    mode: "complete",
    has_object_ids: true,
    object_count: 2,
  },
  objects: [
    { object_id: 0, gaussian_count: 6, chunk_ids: [0] },
    { object_id: 1, gaussian_count: 6, chunk_ids: [1] },
  ],
  chunks: [
    {
      chunk_id: 0,
      object_id: 0,
      gaussian_count: 6,
      record_count: 6,
      record_format: QUANTIZED_OGC_RECORD_FORMAT,
      byte_offset: 0,
      byte_length: 6 * QUANTIZED_OGC_RECORD_BYTE_SIZE,
      aabb_min: [-0.6, 0, -0.35],
      aabb_max: [0.6, 1.2, 0.35],
      lod: {
        schema: "objgauss-object-aware-lod-v1",
        levels: [
          {
            level: 0,
            ratio: 1.0,
            record_count: 6,
            byte_offset: 0,
            byte_length: 6 * QUANTIZED_OGC_RECORD_BYTE_SIZE,
          },
          {
            level: 1,
            ratio: 0.5,
            record_count: 3,
            byte_offset: 0,
            byte_length: 3 * QUANTIZED_OGC_RECORD_BYTE_SIZE,
          },
        ],
      },
    },
    {
      chunk_id: 1,
      object_id: 1,
      gaussian_count: 6,
      record_count: 6,
      record_format: QUANTIZED_OGC_RECORD_FORMAT,
      byte_offset: 6 * QUANTIZED_OGC_RECORD_BYTE_SIZE,
      byte_length: 6 * QUANTIZED_OGC_RECORD_BYTE_SIZE,
      aabb_min: [1.4, 0, -0.45],
      aabb_max: [2.4, 1.3, 0.45],
      lod: {
        schema: "objgauss-object-aware-lod-v1",
        levels: [
          {
            level: 0,
            ratio: 1.0,
            record_count: 6,
            byte_offset: 6 * QUANTIZED_OGC_RECORD_BYTE_SIZE,
            byte_length: 6 * QUANTIZED_OGC_RECORD_BYTE_SIZE,
          },
          {
            level: 1,
            ratio: 0.5,
            record_count: 3,
            byte_offset: 6 * QUANTIZED_OGC_RECORD_BYTE_SIZE,
            byte_length: 3 * QUANTIZED_OGC_RECORD_BYTE_SIZE,
          },
        ],
      },
    },
  ],
};

export const MODEL_CATALOG = [
  {
    id: "plush",
    name: "Plush object scene",
    label: "Plush",
    sourcePath: "/samples/plush_objects.ply",
    loadMode: "eager",
    kind: "object-aware-ply",
    stage: "processed",
    objectCount: 3,
    galleryPosition: [-6.2, 0, -1.35],
    accent: "#ff6b7a",
    displayScale: 2.42,
    pointSize: 0.034,
    minObjectDisplaySpan: 1.22,
    maxObjectDisplayBoost: 5.2,
    maxDisplayPoints: 34000,
    compression: {
      layout: "per-object-corepoint-chunks",
      status: "planned",
      chunkRoot: "/models/plush/objects/",
    },
  },
  {
    id: "plush-v1",
    name: "ObjGauss v1 closure",
    label: "Plush v1",
    sourcePath: "/samples/plush_v1_objects.ply",
    loadMode: "eager",
    kind: "object-aware-ply",
    stage: "processed",
    objectCount: 4,
    galleryPosition: [-3.15, 0, 1.55],
    accent: "#f7b267",
    displayScale: 2.34,
    pointSize: 0.034,
    minObjectDisplaySpan: 1.08,
    maxObjectDisplayBoost: 4.6,
    maxDisplayPoints: 34000,
    compression: {
      layout: "per-object-corepoint-chunks",
      status: "planned",
      chunkRoot: "/models/plush-v1/objects/",
    },
  },
  {
    id: "lego-alpha",
    name: "Lego alpha closure",
    label: "Lego alpha",
    sourcePath: "/samples/lego_alpha_v1_objects.ply",
    loadMode: "eager",
    kind: "object-aware-ply",
    stage: "processed",
    objectCount: 5,
    galleryPosition: [0.05, 0, -1.25],
    accent: "#27c2cb",
    displayScale: 2.46,
    pointSize: 0.035,
    minObjectDisplaySpan: 1.08,
    maxObjectDisplayBoost: 4.8,
    maxDisplayPoints: 26000,
    compression: {
      layout: "per-object-corepoint-chunks",
      status: "planned",
      chunkRoot: "/models/lego-alpha/objects/",
    },
  },
  {
    id: "polyhaven-chair",
    name: "Poly Haven chair",
    label: "Chair",
    sourcePath: "/samples/polyhaven_chair_demo_objects.ply",
    loadMode: "eager",
    kind: "object-aware-ply",
    stage: "processed",
    objectCount: 1,
    galleryPosition: [3.25, 0, 1.42],
    accent: "#88d498",
    displayScale: 2.14,
    pointSize: 0.033,
    maxDisplayPoints: 36000,
    compression: {
      layout: "per-object-corepoint-chunks",
      status: "planned",
      chunkRoot: "/models/polyhaven-chair/objects/",
    },
  },
  {
    id: "near1m-lego",
    name: "Near-1M Lego candidate",
    label: "Near-1M",
    sourcePath: "/samples/nerf_lego_trained_near1m_random1300k_objects.ply",
    loadMode: "compressed-placeholder",
    kind: "diagnostic-ply",
    stage: "diagnostic",
    objectCount: 5,
    galleryPosition: [6.35, 0, -1.42],
    accent: "#8e6cff",
    displayScale: 2.28,
    pointSize: 0.042,
    placeholderPointsPerObject: 820,
    maxDisplayPoints: 45000,
    compression: {
      layout: "per-object-corepoint-chunks",
      status: "prototype",
      chunkRoot: "/models/near1m-lego/objects/",
    },
  },
  {
    id: "ogc-debug",
    name: "OGC chunk debug fixture",
    label: "OGC chunks",
    loadMode: "ogc-chunked",
    kind: "compressed-chunked-ogc",
    stage: "browser-delivery-fixture",
    objectCount: 2,
    galleryPosition: [0.18, 0, 3.25],
    accent: "#2fd3a6",
    displayScale: 1.88,
    pointSize: 0.058,
    maxDisplayPoints: 1200,
    ogc: {
      lodLevel: 0,
    },
    compression: {
      layout: "object-aware-quantized-ogc-chunks",
      status: "browser-ready",
      chunkRoot: "/models/ogc-debug/objects/",
    },
    modelArtifactManifest: {
      schema: MODEL_ARTIFACT_MANIFEST_SCHEMA,
      manifest_id: "ogc-debug-model-artifacts",
      asset_id: "ogc-debug",
      name: "OGC chunk debug fixture",
      stage: "development",
      source: {
        type: "object_aware_gaussian_codec_fixture",
        input: "inline quantized OGC records",
      },
      license: "fixture",
      counts: {
        gaussians: OGC_DEBUG_INDEX.gaussian_count,
        objects: OGC_DEBUG_INDEX.object_count,
      },
      artifacts: [
        {
          role: "compressed_chunked",
          path: "inline://ogc-debug.ogc",
          format: ".ogc",
          delivery_tier: "browser_edit",
          browser_ready: true,
          gaussian_count: OGC_DEBUG_INDEX.gaussian_count,
          object_count: OGC_DEBUG_INDEX.object_count,
          byte_size: OGC_DEBUG_INDEX.payload.byte_size,
          sha256: OGC_DEBUG_INDEX.payload.sha256,
          chunk_index: {
            schema: OGC_DEBUG_INDEX.schema,
            path: "inline://ogc-debug.index.json",
            chunk_count: OGC_DEBUG_INDEX.chunks.length,
            sort_key: OGC_DEBUG_INDEX.sort_key,
            chunk_size_target: OGC_DEBUG_INDEX.chunk_size_target,
          },
          compression: OGC_DEBUG_INDEX.compression,
          lod: OGC_DEBUG_INDEX.lod,
          object_id_coverage: OGC_DEBUG_INDEX.object_id_coverage,
          inlineIndex: OGC_DEBUG_INDEX,
          payloadBase64: OGC_DEBUG_PAYLOAD_BASE64,
        },
      ],
      quality_evidence: [
        {
          kind: "browser_decoder_contract",
          status: "fixture",
          decoded_gaussians: OGC_DEBUG_INDEX.gaussian_count,
        },
      ],
      limitations: ["Tiny inline fixture for browser OGC delivery wiring; not a trained scene."],
      created_from: {
        source: "OGC-BROWSER-STREAMING-001",
      },
    },
  },
  {
    id: "trainable-mvp-debug",
    name: "Trainable MVP artifact",
    label: "Trainable MVP",
    loadMode: "trainable-artifact",
    kind: "trainable-kernel-model-artifact",
    stage: "debug-fixture",
    objectCount: 2,
    galleryPosition: [-2.65, 0, 3.62],
    accent: "#f3df5d",
    displayScale: 1.92,
    pointSize: 0.082,
    maxDisplayPoints: 128,
    trainableArtifact: TRAINABLE_MVP_DEBUG_ARTIFACT,
    compression: {
      layout: "trainable-kernel-artifact-json",
      status: "debug-fixture",
      chunkRoot: "/models/trainable-mvp-debug/objects/",
    },
  },
];

export function catalogSummary(models = MODEL_CATALOG) {
  return {
    modelCount: models.length,
    compressedReadyCount: models.filter((model) =>
      ["prototype", "browser-ready"].includes(model.compression?.status),
    ).length,
    processedCount: models.filter((model) => model.stage === "processed").length,
  };
}
