export const WEBGPU_RUNTIME_PROBE_FULL = "full";
export const WEBGPU_RUNTIME_PROBE_ACCUMULATION_ONLY = "accumulation-only";
export const WEBGPU_RUNTIME_PROBE_RESOLVE_ONLY = "resolve-only";
export const WEBGPU_RUNTIME_PROBE_PIXEL_OUTPUT_ONLY = "pixel-output-only";
export const WEBGPU_RUNTIME_PROBE_PIXEL_COMPUTE_ONLY = "pixel-compute-only";
export const WEBGPU_RUNTIME_PROBE_DISPLAY_ONLY = "display-only";
export const WEBGPU_RUNTIME_PROBE_TINY_PIXEL_OUTPUT = "tiny-pixel-output";
export const WEBGPU_RUNTIME_PROBE_TINY_VIEWPORT_SIZE = 32;

export const WEBGPU_RUNTIME_PROBE_MODES = Object.freeze([
  WEBGPU_RUNTIME_PROBE_FULL,
  WEBGPU_RUNTIME_PROBE_ACCUMULATION_ONLY,
  WEBGPU_RUNTIME_PROBE_RESOLVE_ONLY,
  WEBGPU_RUNTIME_PROBE_PIXEL_OUTPUT_ONLY,
  WEBGPU_RUNTIME_PROBE_PIXEL_COMPUTE_ONLY,
  WEBGPU_RUNTIME_PROBE_DISPLAY_ONLY,
  WEBGPU_RUNTIME_PROBE_TINY_PIXEL_OUTPUT,
]);

const WEBGPU_RUNTIME_PROBE_SET = new Set(WEBGPU_RUNTIME_PROBE_MODES);

export function normalizeWebGpuRuntimeProbe(value) {
  return WEBGPU_RUNTIME_PROBE_SET.has(value)
    ? value
    : WEBGPU_RUNTIME_PROBE_FULL;
}
